### **Machine Learning: aplicado a dados imobilísticos do Paquistão**
Equipe: Gabriel Souza Dunkel, Guilherme Henriques Almeida, Luca Torres Villela

In [1]:
import pandas as pd

pd.options.display.max_rows = None
df = pd.read_csv('pakistan_house_prices.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99499 entries, 0 to 99498
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     99499 non-null  int64
 1   property_type  99499 non-null  object
 2   price          99499 non-null  int64
 3   location       99499 non-null  object
 4   city           99499 non-null  object
 5   baths          99499 non-null  int64
 6   purpose        99499 non-null  object
 7   bedrooms       99499 non-null  int64
 8   Area_in_Marla  99499 non-null  float64
dtypes: float64(1), int64(4), object(4)
memory usage: 6.8+ MB

In [2]:
df.head(10)

,Unnamed: 0,property_type,price,location,city,baths,purpose,bedrooms,Area_in_Marla
0,0,Flat,10000000,G-10,Islamabad,2,For Sale,2,4.0
1,1,Flat,6900000,E-11,Islamabad,3,For Sale,3,5.6
2,2,House,16500000,G-15,Islamabad,6,For Sale,5,8.0
3,3,House,43500000,Bani Gala,Islamabad,4,For Sale,4,40.0
4,4,House,7000000,DHA Defence,Islamabad,3,For Sale,3,8.0
5,7,Flat,7800000,E-11,Islamabad,2,For Sale,2,6.2
6,9,Penthouse,40000000,F-11,Islamabad,5,For Sale,5,20.0
7,10,Flat,35000000,Diplomatic Enclave,Islamabad,3,For Sale,3,7.1
8,13,Flat,13500000,DHA Defence,Islamabad,5,For Sale,3,10.0
9,14,Flat,3600000,E-11,Islamabad,1,For Sale,1,3.1

### **Tipo de cada coluna:**
- unnamed: Categórica e Nominal (um tipo de id)
- property_type: Categórica e Nominal
- price: Numérica e Razão
- location: Categórica e Nominal
- city: Categórica e Nominal
- baths e bedrooms: Numérica e Razão
- purpose: Categórica e Nominal (For sale, for rent)
- Area_in_marla: Numérica e Razão

### **Tratamentos iniciais necessários**
- A função *info()* nos mostrou que não há dados nulos ou faltantes. Por isso não removeremos linhas e não faremos inputação
- Removeremos a coluna "unnamed" pois é um tipo de ID e não vai ajudar na análise ou predicão de dados
- Finalmente faremos a conversão de Marla para metros quadrados na coluna "Area_in_Marla" para uma melhor compreensão

In [3]:
clean_df = df.copy()
clean_df.drop(columns=['Unnamed: 0'], inplace=True)
clean_df['Area'] = df['Area_in_Marla'] * 25.292852 #converter de Marla pra metro quadrado
clean_df['Area'] = clean_df['Area'].round(0).astype(int) #converter valor pra inteiro pq normalmente é assim em anuncios de imóveis 
clean_df.drop(columns=['Area_in_Marla'], inplace=True)

clean_df.head()

,property_type,price,location,city,baths,purpose,bedrooms,Area
0,Flat,10000000,G-10,Islamabad,2,For Sale,2,101
1,Flat,6900000,E-11,Islamabad,3,For Sale,3,142
2,House,16500000,G-15,Islamabad,6,For Sale,5,202
3,House,43500000,Bani Gala,Islamabad,4,For Sale,4,1012
4,House,7000000,DHA Defence,Islamabad,3,For Sale,3,202